name: Terraform DEV Deploy ...
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
permissions:
    id-token: write
    contents: read
jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dev
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: AWS Access using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Our previously created OpenID Connect in AWS / IAM
          role-to-assume: arn:aws:iam::984912522251:role/github-oidc
          aws-region: eu-north-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dev
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: AWS Access using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Our previously created OpenID Connect in AWS / IAM
          role-to-assume: arn:aws:iam::984912522251:role/github-oidc
          aws-region: eu-north-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=dev.tfvars
